name: Lint & Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Установка Bun
      - name: Install Bun
        uses: oven-sh/bun-action@v2
        with:
          bun-version: latest

      # 3️⃣ Установка зависимостей
      - name: Install dependencies
        run: bun install

      # 4️⃣ Линтинг кода
      - name: Lint
        run: bun lint

      # 5️⃣ Логин в GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Сборка Docker образа
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/StikerlottieBot:latest
          docker build -t $IMAGE_NAME .

      # 7️⃣ Пуш Docker образа в GHCR
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/StikerlottieBot:latest
          docker push $IMAGE_NAME
